export function renderConsole(results) {
  const rows = results.map((row) => ({
    query: row.name,
    rows: row.rows,
    path: row.lakeql.path,
    "work units": row.lakeql.workUnits,
    "lakeql median ms": row.lakeql.medianMs.toFixed(2),
    "lakeql p95 ms": row.lakeql.p95Ms.toFixed(2),
    "duckdb median ms": row.duckdb.medianMs.toFixed(2),
    "duckdb p95 ms": row.duckdb.p95Ms.toFixed(2),
    "lakeql peak rss": formatBytes(row.lakeql.peakRssBytes),
    "lakeql requests": row.lakeql.requests,
    "lakeql bytes": row.lakeql.bytes,
    "files read/skipped": statPair(row.lakeql.filesRead, row.lakeql.filesSkipped),
    "decoded/matched": statPair(row.lakeql.rowsScanned, row.lakeql.rowsMatched),
  }));
  console.table(rows);
  return "";
}

export function renderReport(results, options) {
  const generatedAt = new Date().toISOString().slice(0, 10);
  const headers = [
    "Query",
    "Rows",
    "lakeql median ms",
    "lakeql p95 ms",
    "DuckDB median ms",
    "DuckDB p95 ms",
    "Ratio",
    "lakeql peak RSS",
    "DuckDB peak RSS",
    "lakeql path",
    "work units",
    "lakeql req",
    "lakeql bytes",
    "lakeql ranges",
    "Files read/skipped",
    "Rows decoded/matched",
    "RG read/skipped",
  ];
  const rows = results.map((row) => [
    row.name,
    String(row.rows),
    row.lakeql.medianMs.toFixed(2),
    row.lakeql.p95Ms.toFixed(2),
    row.duckdb.medianMs.toFixed(2),
    row.duckdb.p95Ms.toFixed(2),
    ratio(row.lakeql.medianMs, row.duckdb.medianMs),
    formatBytes(row.lakeql.peakRssBytes),
    formatBytes(row.duckdb.peakRssBytes),
    row.lakeql.path,
    String(row.lakeql.workUnits),
    String(row.lakeql.requests),
    String(row.lakeql.bytes),
    String(row.lakeql.rangeRequests),
    statPair(row.lakeql.filesRead, row.lakeql.filesSkipped),
    statPair(row.lakeql.rowsScanned, row.lakeql.rowsMatched),
    statPair(row.lakeql.rowGroupsRead, row.lakeql.rowGroupsSkipped),
  ]);
  return `# DuckDB Comparison Benchmarks

Generated by \`pnpm bench:duckdb\` on ${generatedAt}.

Each query is run against the same fixture data through lakeql and DuckDB's \`read_parquet\`.
The harness checks result parity before timing. Timings are local and machine-dependent; lakeql
request, byte, and row-group counters are the more stable regression signals.

Iterations: ${options.iterations}; warmup: ${options.warmup}.

${markdownTable(headers, rows)}
`;
}

function statPair(left, right) {
  if (left === "" && right === "") return "";
  return `${left}/${right}`;
}

function formatBytes(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(1)} MiB`;
}

function ratio(left, right) {
  if (right === 0) return "n/a";
  return `${(left / right).toFixed(2)}x`;
}

function markdownTable(headers, rows) {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ].join("\n");
}
